'use client';
import {useEffect,useRef,useState} from 'react';
import MediaLab from './media-lab';
import type {SkillUnit} from './lib/skill-unit';
type Data=Record<string,any>;
export default function SkillPath({action,onDirty,read,review}:{action:(body:Data,message?:string,reload?:boolean)=>Promise<any>;onDirty:(dirty:boolean)=>void;read:()=>void;review:()=>void}) {
 const [unit,setUnit]=useState<SkillUnit|null>(null),[state,setState]=useState<Data|null>(null),[history,setHistory]=useState<Data[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false),[tab,setTab]=useState('listen');
 const [writing,setWriting]=useState(''),[speaking,setSpeaking]=useState(''),[checks,setChecks]=useState<boolean[]>([false,false,false,false]),[speechChecks,setSpeechChecks]=useState<boolean[]>([false,false,false]),[answers,setAnswers]=useState<number[]>([-1,-1,-1]);
 const [showTranscript,setShowTranscript]=useState(false),[transcriptViewed,setTranscriptViewed]=useState(false),[audioPlayed,setAudioPlayed]=useState(false),[playing,setPlaying]=useState(false),[rate,setRate]=useState(1),[audioError,setAudioError]=useState('');
 const utterance=useRef<SpeechSynthesisUtterance|null>(null),alive=useRef(true),timeout=useRef<ReturnType<typeof setTimeout>|null>(null);
 const dirty=!!state && (writing!==(state.writing || '') || speaking!==(state.speaking || '') || JSON.stringify(checks)!==JSON.stringify(state.writingReview?.checks || [false,false,false,false]) || JSON.stringify(speechChecks)!==JSON.stringify(state.speakingReview?.checks || [false,false,false]) || JSON.stringify(answers)!==JSON.stringify(state.listening?.answers || [-1,-1,-1]));
 useEffect(()=>{onDirty(dirty);return ()=>onDirty(false);},[dirty,onDirty]);
 function stop(){utterance.current=null;if('speechSynthesis' in window) speechSynthesis.cancel();if(timeout.current)clearTimeout(timeout.current);setPlaying(false);}
 useEffect(()=>{alive.current=true;const hide=()=>{if(document.hidden)stop();};document.addEventListener('visibilitychange',hide);return ()=>{alive.current=false;document.removeEventListener('visibilitychange',hide);if(timeout.current)clearTimeout(timeout.current);if('speechSynthesis' in window)speechSynthesis.cancel();};},[]);
 function adopt(d:Data){setUnit(d.unit);setState(d.state);setHistory(d.history || []);setWriting(d.state?.writing || '');setSpeaking(d.state?.speaking || '');setChecks(d.state?.writingReview?.checks || [false,false,false,false]);setSpeechChecks(d.state?.speakingReview?.checks || [false,false,false]);setAnswers(d.state?.listening?.answers || [-1,-1,-1]);}
 async function load(){setError('');try{const r=await fetch('/api/pilot?view=skill_path',{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw Error(d.error);if(alive.current)adopt(d);}catch(e){if(alive.current)setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function submit(operation:string){if(!state || saving)return;setSaving(true);const body:Data={op:'path_update',operation,expectedRevision:state.revision,...(operation==='listen'?{answers,transcriptViewed,audioPlayed}:{text:operation==='speak'?speaking:writing,...(operation==='write'?{checks}:operation==='speak'?{checks:speechChecks}:{})})};try{const result=await action(body,operation==='draft'?'Đã lưu phiên bản nháp.':'Đã lưu hoạt động.',true);if(result){setState(result);setHistory(h=>[{operation,at:result.updated,revision:result.revision,writing:['draft','write'].includes(operation)?result.writing:undefined,review:operation==='write'?result.writingReview:undefined},...h]);}}finally{setSaving(false);}}
 function play(){stop();setAudioError('');if(!('speechSynthesis' in window)){setAudioError('Trình duyệt chưa hỗ trợ giọng đọc. Bạn có thể mở transcript để tiếp tục.');return;}const u=new SpeechSynthesisUtterance(unit!.listening.transcript);utterance.current=u;u.lang='en-US';u.rate=rate;u.onstart=()=>{if(alive.current && utterance.current===u){setPlaying(true);setAudioPlayed(true);if(timeout.current)clearTimeout(timeout.current);timeout.current=setTimeout(()=>{if(alive.current){stop();setAudioError('Đã dừng lượt phát quá thời gian. Bạn có thể phát lại.');}},180000);}};u.onend=()=>{if(utterance.current!==u)return;if(alive.current)setPlaying(false);if(timeout.current)clearTimeout(timeout.current);};u.onerror=()=>{if(alive.current && utterance.current===u){setPlaying(false);setAudioError('Không phát được giọng đọc. Hãy thử lại hoặc dùng transcript.');}};setPlaying(true);speechSynthesis.speak(u);timeout.current=setTimeout(()=>{if(alive.current && utterance.current===u){stop();setAudioError('Giọng đọc chưa khởi động. Hãy thử trình duyệt khác hoặc mở transcript.');}},8000);}
 if(!unit)return <div className="card" role="status">{error || 'Đang tải hành trình…'}{error && <button className="secondary" onClick={load}>Thử lại</button>}</div>;
 return <><div className="page-heading"><div><p className="eyebrow">ĐỌC · NGHE · NÓI · VIẾT · ÔN</p><h1>{unit.title}</h1><p>{unit.level} · Chia thành nhiều buổi theo thời gian của bạn.</p></div></div><div className="notice"><p>{unit.provenance} Phần nghe dùng giọng tổng hợp của trình duyệt; phần nói và viết do bạn tự đối chiếu, chưa chấm bằng AI.</p></div><div className="toolbar"><button className="secondary" onClick={read}>1. Đọc bài gốc</button><button className="secondary" onClick={review}>5. Ôn từ đã lưu</button></div>
 {!state?<div className="card"><h2>Bắt đầu một hành trình</h2><p>Nghe hội thoại tại quán, giải thích cách mượn cốc, rồi viết email đề xuất cải thiện.</p><button className="btn" disabled={saving} onClick={async()=>{setSaving(true);try{const d=await action({op:'path_start'},'Đã mở hành trình.');if(d)adopt(d);}finally{setSaving(false);}}}>Bắt đầu hành trình</button></div>:<>
 <div className="card"><p>Đã làm bài nghe: {state.listening?'Có':'Chưa'} · Đã tự đối chiếu nói: {state.speakingReview?'Có':'Chưa'} · Bản viết hiện tại đã tự đối chiếu: {state.writingReview?.text===writing?'Có':'Chưa'}</p><p className="small" role="status">{saving?'Đang lưu…':dirty?'Có thay đổi chưa lưu. Hãy lưu từng phần trước khi rời trang.':'Đã khớp với dữ liệu lưu trên máy chủ.'} · Phiên bản {state.revision}</p></div>
 <div className="toolbar" role="group" aria-label="Chọn kỹ năng">{[['listen','2. Nghe'],['speak','3. Nói'],['write','4. Viết']].map(([key,label])=><button key={key} aria-pressed={tab===key} className={tab===key?'btn':'secondary'} onClick={()=>{stop();setTab(key);}}>{label}</button>)}</div>
 {tab==='listen' && <div className="card stack"><h2>{unit.listening.title}</h2><p>Thử nghe trước khi mở transcript. Mỗi lượt gửi lưu riêng; kết quả lần đầu được giữ lại.</p><label className="form-label">Tốc độ đọc<select value={rate} disabled={playing} onChange={e=>setRate(Number(e.target.value))}><option value={.8}>Chậm 0.8×</option><option value={1}>Thường 1×</option></select></label><div className="toolbar"><button className="btn" onClick={play}>{playing?'Phát lại từ đầu':'Phát hội thoại'}</button><button className="secondary" onClick={stop} disabled={!playing}>Dừng đọc</button><button className="secondary" aria-expanded={showTranscript} onClick={()=>{setShowTranscript(!showTranscript);setTranscriptViewed(true);}}>{showTranscript?'Ẩn transcript':'Mở transcript'}</button></div>{audioError && <p role="alert">{audioError}</p>}{showTranscript && <blockquote lang="en">{unit.listening.transcript}</blockquote>}{unit.listening.questions.map((q,i)=><fieldset key={q.id} className="question" disabled={saving}><legend>{i+1}. {q.prompt}</legend>{q.options.map((o,j)=><label className="option" key={o}><input type="radio" name={'listen-'+q.id} checked={answers[i]===j} onChange={()=>setAnswers(a=>a.map((n,k)=>k===i?j:n))}/>{o}</label>)}</fieldset>)}<button className="btn" disabled={saving || answers.includes(-1)} onClick={()=>submit('listen')}>Gửi câu trả lời nghe</button>{state.listening && <div className="feedback"><b>Kết quả lần {state.listening.attempt}: {state.listening.correct.filter(Boolean).length}/{unit.listening.questions.length}</b>{unit.listening.questions.map((q,i)=><p key={q.id}>Câu {i+1}: {state.listening.correct[i]?'Đúng':'Cần đối chiếu'} · {q.options[state.listening.answerKey[i]]}</p>)}<p className="small">Lần đầu: {state.firstListening.correct.filter(Boolean).length}/{unit.listening.questions.length} · {state.firstListening.transcriptViewed?'Đã mở transcript':'Chưa ghi nhận mở transcript'}; đây là bài luyện, không phải điểm năng lực nghe chuẩn hóa.</p></div>}</div>}
 {tab==='speak' && <div className="grid-2"><div className="card stack"><h2>{unit.speaking.title}</h2><p>Đọc lần lượt lời hỏi của người bạn và trả lời thành tiếng. Có thể gõ ý chính nếu không dùng micro.</p>{unit.speaking.turns.map((t,i)=><blockquote lang="en" key={t}>{i+1}. {t}</blockquote>)}<label className="form-label">Ý chính / câu bạn muốn nói lại<textarea maxLength={6000} value={speaking} onChange={e=>setSpeaking(e.target.value)}/></label>{unit.speaking.criteria.map((c,i)=><label className="check" key={c}><input type="checkbox" checked={speechChecks[i]} onChange={e=>setSpeechChecks(a=>a.map((v,j)=>i===j?e.target.checked:v))}/>{c}</label>)}<button className="btn" disabled={saving || !speaking.trim()} onClick={()=>submit('speak')}>Lưu tự đối chiếu nói</button></div><MediaLab mode="speech" onTranscript={t=>setSpeaking(t)}/></div>}
 {tab==='write' && <div className="grid-2"><div className="card stack"><h2>Email đề xuất</h2><p lang="en">{unit.writing.prompt}</p><label className="form-label">Bản viết của bạn<textarea style={{minHeight:300}} maxLength={6000} value={writing} onChange={e=>setWriting(e.target.value)}/></label><p className="small">{writing.trim()?writing.trim().split(/\s+/).length:0} từ · Mục tiêu 100–140 từ</p><button className="secondary" disabled={saving} onClick={()=>submit('draft')}>Lưu phiên bản nháp</button>{state.writingReview && <p className="small">{state.writingReview.text===writing?'Tự đối chiếu đang gắn với đúng bản viết này.':'Bản viết đã thay đổi. Tự đối chiếu cũ chỉ thuộc phiên bản trước; hãy đối chiếu lại.'}</p>}</div><div className="card stack"><h2>Tự đối chiếu bài viết</h2>{unit.writing.criteria.map((c,i)=><label className="check" key={c}><input type="checkbox" checked={checks[i]} onChange={e=>setChecks(a=>a.map((v,j)=>i===j?e.target.checked:v))}/>{c}</label>)}<p className="small">Đánh dấu điều bạn đã làm; mục chưa đạt có thể để trống. Đây là đánh giá của bạn, không phải nhận xét của giáo viên hoặc AI.</p><button className="btn" disabled={saving || writing.trim().split(/\s+/).length<20} onClick={()=>submit('write')}>Lưu bản viết và tự đối chiếu</button><details><summary>Khung email tham khảo</summary><p style={{whiteSpace:'pre-wrap'}} lang="en">{unit.writing.example}</p></details></div></div>}
 <div className="card"><h2>Lịch sử hành trình</h2><p className="small">Giữ các phiên bản đã lưu. Sao chép đoạn cần dùng từ lịch sử để sửa tiếp; không tự áp dụng nhận xét cũ lên bản mới.</p>{history.slice(0,30).map(h=><details className="post" key={h.revision}><summary>Phiên bản {h.revision} · {({draft:'Lưu nháp',write:'Tự đối chiếu viết',listen:'Bài nghe',speak:'Tự đối chiếu nói'} as Data)[h.operation]} · {new Date(h.at).toLocaleString('vi-VN')}</summary>{h.writing && <p style={{whiteSpace:'pre-wrap'}}>{h.writing}</p>}{h.review && <p>Đã tự đánh dấu {h.review.checks.filter(Boolean).length}/{unit.writing.criteria.length} tiêu chí.</p>}</details>)}<p className="small">Hiện tối đa 30 hoạt động. Xuất dữ liệu cá nhân để lấy đầy đủ.</p><button className="secondary" disabled={saving} onClick={()=>{if(!dirty || window.confirm('Tải dữ liệu đã lưu sẽ bỏ thay đổi chưa lưu trên trang này. Tiếp tục?'))void load();}}>Tải bản đã lưu</button></div>
 </>}{error && <p role="alert">{error}</p>}</>;
}
